const traducciones = {
  es: {
    inicio: "Inicio",
    pedido: "Pedido",
    idioma: "Idioma",
    Entrantes: "Entrantes",
    "Platos principales": "Platos principales",
    "Wraps y Bocadillos": "Wraps y Bocadillos",
    "Especialidades Internacionales": "Especialidades Internacionales",
    Postres: "Postres",
    Bebidas: "Bebidas",
    mas: "más",
    menos: "menos",
    detalles: "Detalles",
    alergenos: "Alérgenos",
    calorias: "Calorías",
    volver: "Volver",
    menu: "Menú",
    titulo: "Bienvenido a la Carta Digital 🍽",
    vacio: "No has añadido platos aún.",
    total: "Total",
    volverCarta: "Volver a la carta",
    añadido: "Se ha añadido",
    al_pedido: "al pedido",
  },
  en: {
    inicio: "Home",
    pedido: "Order",
    idioma: "Language",
    Entrantes: "Starters",
    "Platos principales": "Main Dishes",
    "Wraps y Bocadillos": "Wraps & Sandwiches",
    "Especialidades Internacionales": "International Specialties",
    Postres: "Desserts",
    Bebidas: "Drinks",
    mas: "more",
    menos: "less",
    detalles: "Details",
    alergenos: "Allergens",
    calorias: "Calories",
    volver: "Back",
    menu: "Menu",
    titulo: "Welcome to the Digital Menu 🍽",
    vacio: "You haven't added any dishes yet.",
    total: "Total",
    volverCarta: "Back to menu",
    añadido: "Added",
    al_pedido: "to the order",
  },
  fr: {
    inicio: "Accueil",
    pedido: "Commande",
    idioma: "Langue",
    Entrantes: "Entrées",
    "Platos principales": "Plats principaux",
    "Wraps y Bocadillos": "Wraps et Sandwichs",
    "Especialidades Internacionales": "Spécialités internationales",
    Postres: "Desserts",
    Bebidas: "Boissons",
    mas: "plus",
    menos: "moins",
    detalles: "Détails",
    alergenos: "Allergènes",
    calorias: "Calories",
    volver: "Retour",
    menu: "Menu",
    titulo: "Bienvenue dans le Menu Numérique 🍽",
    vacio: "Vous n'avez encore ajouté aucun plat.",
    total: "Total",
    volverCarta: "Retour au menu",
    añadido: "Ajouté",
    al_pedido: "à la commande",
  },
  it: {
    inicio: "Home",
    pedido: "Ordine",
    idioma: "Lingua",
    Entrantes: "Antipasti",
    "Platos principales": "Piatti principali",
    "Wraps y Bocadillos": "Wrap e Panini",
    "Especialidades Internacionales": "Specialità internazionali",
    Postres: "Dolci",
    Bebidas: "Bevande",
    mas: "più",
    menos: "meno",
    detalles: "Dettagli",
    alergenos: "Allergeni",
    calorias: "Calorie",
    volver: "Indietro",
    menu: "Menù",
    titulo: "Benvenuti nel Menu Digitale 🍽",
    vacio: "Non hai ancora aggiunto piatti.",
    total: "Totale",
    volverCarta: "Torna al menu",
    añadido: "Aggiunto",
    al_pedido: "all'ordine",
  },
};

export default traducciones;
